export interface GlossaryEntry {
  slug: string;
  term: string;
  category: 'work' | 'comp' | 'legal' | 'culture' | 'tech';
  short: string;
  long: string;
}

export const GLOSSARY: GlossaryEntry[] = [
  { slug: 'async', term: 'Async (Asynchronous communication)', category: 'work', short: "Communicating without expecting real-time replies.", long: 'Default working pattern of mature remote teams. Decisions written down, discussions happening across hours not minutes, video calls reserved for irreducibly synchronous work.' },
  { slug: 'rto', term: 'RTO (Return To Office)', category: 'work', short: 'Corporate policy bringing employees back to in-person work.', long: 'Most large US tech employers announced RTO between 2022 and 2024, typically requiring three days a week on site. Most remote-first companies have not.' },
  { slug: 'wfh', term: 'WFH (Work From Home)', category: 'work', short: 'Working remotely from a residential setting.', long: 'Often used interchangeably with remote work, though WFH technically excludes travel-based remote (digital nomad) setups.' },
  { slug: 'remote-first', term: 'Remote-first', category: 'culture', short: 'Company where remote is the default operating mode.', long: 'Distinct from remote-friendly: remote-first companies design processes, tooling, and culture around distributed work. Documentation is mandatory, meetings are exceptional, hiring is geography-agnostic.' },
  { slug: 'remote-friendly', term: 'Remote-friendly', category: 'culture', short: 'Company that allows remote work but defaults to in-office.', long: 'Many remote-friendly companies provide a worse remote experience than remote-first peers because culture and tooling still privilege those in the office.' },
  { slug: 'hybrid', term: 'Hybrid work', category: 'work', short: 'Mix of remote and in-office days.', long: 'Typically one to three days in office per week. The dominant pattern at most large tech employers in 2026 outside of remote-first scale-ups.' },
  { slug: 'distributed-team', term: 'Distributed team', category: 'culture', short: 'Team whose members live in multiple cities or countries.', long: 'Distributed is broader than remote: a distributed team may have multiple physical offices in different regions, while a remote team typically has no office at all.' },
  { slug: 'timezone-overlap', term: 'Timezone overlap', category: 'work', short: 'Hours when two distributed teammates are both working.', long: 'The single most filtered criterion on remote engineering postings in 2026. Four hours of overlap is the working minimum for most synchronous-leaning roles; two hours works for IC-deep work.' },
  { slug: 'eor', term: 'EOR (Employer of Record)', category: 'legal', short: 'Third-party that legally employs a worker on behalf of a foreign company.', long: 'Common solution when a US-based company wants to hire an EU resident. The EOR (Deel, Remote.com, Oyster) handles local payroll, tax, and compliance. Typically costs the employer 400 to 900 USD per month per employee.' },
  { slug: 'ic', term: 'IC (Individual Contributor)', category: 'work', short: 'Engineer who builds, distinct from a manager.', long: 'The IC track typically extends from junior through senior, staff, principal, and distinguished levels. Many remote-first companies favor strong IC ladders over management progression.' },
  { slug: 'pip', term: 'PIP (Performance Improvement Plan)', category: 'work', short: 'Formal documented underperformance process.', long: 'Usually 30 to 90 days. In remote contexts, almost always precedes termination. Treated as termination notice at most US employers.' },
  { slug: 'rsu', term: 'RSU (Restricted Stock Unit)', category: 'comp', short: 'Company stock granted as part of compensation, vesting over time.', long: 'Standard equity vehicle at public tech companies. Vests over four years with a one-year cliff typically. Taxed as ordinary income on vest at most jurisdictions.' },
  { slug: 'esop', term: 'ESOP (Employee Stock Ownership Plan)', category: 'comp', short: 'Pool of company shares reserved for employees.', long: 'At private companies, employee stock options are granted from the ESOP pool. Total ESOP typically sits between 10 and 20 percent of company shares at well-structured startups.' },
  { slug: 'dnv', term: 'DNV (Digital Nomad Visa)', category: 'legal', short: 'Visa category specifically for remote workers employed abroad.', long: 'Roughly 50 countries had a dedicated DNV by 2026. Portugal D8, Spain DNV, Greece DNV, Estonia DNV and Mexico Temporary Resident are the most-used by tech workers.' },
  { slug: 'geo-arbitrage', term: 'Geo-arbitrage', category: 'comp', short: 'Earning in a high-income currency while spending in a low-cost location.', long: 'Common practice among remote workers earning USD or EUR while living in lower-cost regions. Real wealth-builder over multi-year horizons but creates compliance complexity (tax residency, social charges).' },
  { slug: 'permanent-establishment', term: 'Permanent establishment', category: 'legal', short: 'Tax concept where a company is considered to have a taxable presence in a country.', long: 'Risk for employers of remote workers: if an employee performs core business functions in a country where the company has no entity, tax authorities may declare the company has permanent establishment there. EOR services exist primarily to avoid this.' },
  { slug: 'right-to-disconnect', term: 'Right to disconnect', category: 'legal', short: 'Legal protection against work communications outside working hours.', long: 'Enacted in France, Portugal, Spain, Italy, Australia and Ontario. Generally requires employers to respect employee off-hours and to formalize working hour expectations in writing.' },
  { slug: 'okr', term: 'OKR (Objectives and Key Results)', category: 'work', short: 'Goal-setting framework for measurable team outputs.', long: 'Dominant goal-setting framework at remote tech companies. Quarterly cadence with three to five objectives, each broken into measurable key results.' },
  { slug: 'standup', term: 'Standup', category: 'work', short: 'Recurring team sync, usually daily.', long: 'Remote teams typically run async written standups in a shared channel. Synchronous video standups persist but have lost ground since 2022.' },
  { slug: 'sprint', term: 'Sprint', category: 'work', short: 'Time-boxed development cycle, typically two weeks.', long: 'Remote teams often run two-week sprints with planning at the start and a retrospective at the end. Asynchronous sprint planning has emerged as a viable alternative to the traditional synchronous meeting.' },
  { slug: 'retro', term: 'Retrospective', category: 'work', short: 'Team review of what worked and what did not.', long: 'Typically at the end of each sprint. Remote teams often run async retros via collaborative documents like Miro or shared docs, with synchronous review only of the discussion items.' },
  { slug: 'ats', term: 'ATS (Applicant Tracking System)', category: 'work', short: 'Software that companies use to manage candidate pipelines.', long: 'Greenhouse, Lever and Workday dominate. The actual job listings on most company career sites are powered by an ATS. Aggregators like slateremote.com pull from these ATS APIs.' },
  { slug: 'severance', term: 'Severance', category: 'legal', short: 'Payment made when an employee is terminated without cause.', long: 'Varies enormously: at-will US employment provides no statutory severance; most EU countries mandate at least 1 month per year of service. Negotiating severance at signing is rare but high-value at senior levels.' },
  { slug: 'notice-period', term: 'Notice period', category: 'legal', short: 'Mandatory advance warning before quitting or being terminated.', long: 'Two weeks is standard at US employers. Most EU jurisdictions mandate one to three months. Notice periods are negotiable at signing in many countries.' },
  { slug: 'non-compete', term: 'Non-compete', category: 'legal', short: 'Clause preventing an employee from joining competitors for a period after leaving.', long: 'Banned in California and many EU countries. Enforceable but limited in most US states. Increasingly rare and weakly enforceable in tech in 2026.' },
  { slug: 'nda', term: 'NDA (Non-Disclosure Agreement)', category: 'legal', short: 'Confidentiality obligation about company information.', long: 'Universal at tech employers. NDAs covering interview content (during hiring) are common and legally enforceable.' },
  { slug: 'founding-engineer', term: 'Founding engineer', category: 'work', short: 'Early engineering hire at a startup, typically employees 1 to 10.', long: 'Implies significantly higher equity (0.5 to 2 percent typically) and broader scope than later hires. Most founding engineering roles are not strictly remote even at remote-friendly startups.' },
  { slug: 'staff-engineer', term: 'Staff engineer', category: 'work', short: 'Senior IC level above senior engineer, below principal.', long: 'Roughly 8 to 12 years of experience equivalent. Compensation bands sit at 220 to 320 thousand USD at well-funded remote employers. Significant scope of technical influence beyond individual code.' },
  { slug: 'principal-engineer', term: 'Principal engineer', category: 'work', short: 'Senior IC level above staff.', long: 'Roughly 12 to 20 years of experience equivalent. Often spans multiple teams. Compensation bands at 280 to 450 thousand USD at well-funded remote employers.' },
  { slug: 'ten-x', term: '10x engineer', category: 'culture', short: 'Cliché for an engineer perceived as ten times more productive than the median.', long: 'Largely discredited as a concept. The reality is that engineering effectiveness depends on context, codebase familiarity, and team dynamics far more than individual heroics.' },
  { slug: 'burnout', term: 'Burnout', category: 'culture', short: 'Chronic workplace stress that has not been successfully managed.', long: 'In remote contexts, burnout often manifests as isolation rather than overwork. The combination of lack of separation between work and home plus reduced social signals is the most common driver.' },
  { slug: 'layoff', term: 'Layoff', category: 'legal', short: 'Termination not based on individual performance.', long: 'Tech layoffs hit a multi-year peak in 2023 to 2024 and stabilized by 2026. Severance packages at major employers typically run 2 to 6 months of base salary plus accelerated equity vesting.' },
  { slug: 'pto', term: 'PTO (Paid Time Off)', category: 'comp', short: 'Bank of paid vacation days.', long: 'US norm is 15 to 25 days. EU statutory minimums range from 20 to 30 days plus public holidays. Most remote-first companies offer "unlimited PTO" which in practice averages closer to the US norm than the EU norm.' },
  { slug: 'cv', term: 'CV vs Resume', category: 'work', short: 'Different naming conventions for the application document.', long: 'Resume is US/Canada norm: one page, sometimes two. CV is EU/UK norm: longer, more detail. For remote applications to US companies, default to the US resume convention.' },
  { slug: 't-shape', term: 'T-shape engineer', category: 'culture', short: 'Broad knowledge across many areas plus deep expertise in one.', long: 'The dominant profile that remote engineering teams value: breadth to communicate across boundaries plus depth to ship in one area.' },
  { slug: 'mvp', term: 'MVP (Minimum Viable Product)', category: 'tech', short: 'Smallest version of a product that delivers value to users.', long: 'Used loosely. In practice, most "MVPs" ship with more scope than the term implies. The valuable usage is to constrain scope early in a project.' },
  { slug: 'tdd', term: 'TDD (Test-Driven Development)', category: 'tech', short: 'Writing tests before code.', long: 'Less dogmatic than a decade ago. Most senior engineers practice test-first selectively, particularly for complex logic or external interfaces.' },
  { slug: 'ci-cd', term: 'CI/CD (Continuous Integration / Continuous Deployment)', category: 'tech', short: 'Automated build, test, and deployment pipelines.', long: 'Universal expectation on remote engineering roles. GitHub Actions is the most-listed tool, with GitLab CI second.' },
  { slug: 'slowmad', term: 'Slowmad / Slowmadism', category: 'culture', short: 'Digital nomad lifestyle with longer stays in each location.', long: 'Reaction against fast nomadism (changing cities every few weeks). Slowmads spend three to twelve months per location, integrate more locally, and report better long-term wellbeing.' },
  { slug: 'coworking', term: 'Coworking space', category: 'culture', short: 'Shared workspace open to non-employees of a single company.', long: 'WeWork, Selina, Outsite and many local players dominate. Daily passes typically cost 15 to 35 USD; monthly memberships 200 to 500. Most remote workers split time between home and coworking weekly.' },
];

export const GLOSSARY_MAP: Record<string, GlossaryEntry> = Object.fromEntries(
  GLOSSARY.map((g) => [g.slug, g]),
);
