// Static data for the 2026 FIFA World Cup host cities cluster.
// 11 US cities, 2 Canadian, 3 Mexican. The first 48-team edition.

export interface WC2026City {
  slug: string;
  name: string;
  country: 'US' | 'CA' | 'MX';
  countryName: string;
  countryCode: 'US' | 'CA' | 'MX';
  stadium: string;
  stadiumCapacity: number;
  matchesHosted: number;
  timezone: string;
  /** UTC offset during the tournament (June-July, daylight saving) */
  utcOffset: number;
  currency: 'USD' | 'CAD' | 'MXN';
  /** Median fixed-line internet speed, Mbps */
  internetMbps: number;
  /** Cost index 1 (cheapest) to 5 (priciest) for tournament-period stay */
  costIndex: 1 | 2 | 3 | 4 | 5;
  /** Coworking-friendly neighbourhoods worth basing in */
  baseNeighbourhoods: string[];
}

export const WC2026_CITIES: WC2026City[] = [
  {
    slug: 'atlanta',
    name: 'Atlanta',
    country: 'US',
    countryName: 'United States',
    countryCode: 'US',
    stadium: 'Mercedes-Benz Stadium',
    stadiumCapacity: 71_000,
    matchesHosted: 8,
    timezone: 'America/New_York',
    utcOffset: -4,
    currency: 'USD',
    internetMbps: 300,
    costIndex: 3,
    baseNeighbourhoods: ['Midtown', 'Buckhead', 'Old Fourth Ward'],
  },
  {
    slug: 'boston',
    name: 'Boston',
    country: 'US',
    countryName: 'United States',
    countryCode: 'US',
    stadium: 'Gillette Stadium',
    stadiumCapacity: 65_878,
    matchesHosted: 7,
    timezone: 'America/New_York',
    utcOffset: -4,
    currency: 'USD',
    internetMbps: 350,
    costIndex: 4,
    baseNeighbourhoods: ['Back Bay', 'Cambridge', 'Seaport'],
  },
  {
    slug: 'dallas',
    name: 'Dallas',
    country: 'US',
    countryName: 'United States',
    countryCode: 'US',
    stadium: 'AT&T Stadium',
    stadiumCapacity: 80_000,
    matchesHosted: 9,
    timezone: 'America/Chicago',
    utcOffset: -5,
    currency: 'USD',
    internetMbps: 320,
    costIndex: 3,
    baseNeighbourhoods: ['Uptown', 'Deep Ellum', 'Bishop Arts'],
  },
  {
    slug: 'houston',
    name: 'Houston',
    country: 'US',
    countryName: 'United States',
    countryCode: 'US',
    stadium: 'NRG Stadium',
    stadiumCapacity: 72_220,
    matchesHosted: 7,
    timezone: 'America/Chicago',
    utcOffset: -5,
    currency: 'USD',
    internetMbps: 300,
    costIndex: 3,
    baseNeighbourhoods: ['Montrose', 'The Heights', 'Midtown'],
  },
  {
    slug: 'kansas-city',
    name: 'Kansas City',
    country: 'US',
    countryName: 'United States',
    countryCode: 'US',
    stadium: 'Arrowhead Stadium',
    stadiumCapacity: 76_416,
    matchesHosted: 6,
    timezone: 'America/Chicago',
    utcOffset: -5,
    currency: 'USD',
    internetMbps: 280,
    costIndex: 2,
    baseNeighbourhoods: ['Crossroads', 'Westport', 'River Market'],
  },
  {
    slug: 'los-angeles',
    name: 'Los Angeles',
    country: 'US',
    countryName: 'United States',
    countryCode: 'US',
    stadium: 'SoFi Stadium',
    stadiumCapacity: 70_240,
    matchesHosted: 8,
    timezone: 'America/Los_Angeles',
    utcOffset: -7,
    currency: 'USD',
    internetMbps: 340,
    costIndex: 5,
    baseNeighbourhoods: ['Santa Monica', 'Culver City', 'West Hollywood'],
  },
  {
    slug: 'miami',
    name: 'Miami',
    country: 'US',
    countryName: 'United States',
    countryCode: 'US',
    stadium: 'Hard Rock Stadium',
    stadiumCapacity: 65_326,
    matchesHosted: 7,
    timezone: 'America/New_York',
    utcOffset: -4,
    currency: 'USD',
    internetMbps: 320,
    costIndex: 5,
    baseNeighbourhoods: ['Brickell', 'Wynwood', 'Coconut Grove'],
  },
  {
    slug: 'new-york-new-jersey',
    name: 'New York / New Jersey',
    country: 'US',
    countryName: 'United States',
    countryCode: 'US',
    stadium: 'MetLife Stadium',
    stadiumCapacity: 82_500,
    matchesHosted: 8,
    timezone: 'America/New_York',
    utcOffset: -4,
    currency: 'USD',
    internetMbps: 380,
    costIndex: 5,
    baseNeighbourhoods: ['Brooklyn', 'Lower Manhattan', 'Jersey City'],
  },
  {
    slug: 'philadelphia',
    name: 'Philadelphia',
    country: 'US',
    countryName: 'United States',
    countryCode: 'US',
    stadium: 'Lincoln Financial Field',
    stadiumCapacity: 67_594,
    matchesHosted: 6,
    timezone: 'America/New_York',
    utcOffset: -4,
    currency: 'USD',
    internetMbps: 290,
    costIndex: 3,
    baseNeighbourhoods: ['Center City', 'Fishtown', 'University City'],
  },
  {
    slug: 'san-francisco-bay-area',
    name: 'San Francisco Bay Area',
    country: 'US',
    countryName: 'United States',
    countryCode: 'US',
    stadium: "Levi's Stadium",
    stadiumCapacity: 68_500,
    matchesHosted: 6,
    timezone: 'America/Los_Angeles',
    utcOffset: -7,
    currency: 'USD',
    internetMbps: 400,
    costIndex: 5,
    baseNeighbourhoods: ['Mission', 'SoMa', 'Palo Alto'],
  },
  {
    slug: 'seattle',
    name: 'Seattle',
    country: 'US',
    countryName: 'United States',
    countryCode: 'US',
    stadium: 'Lumen Field',
    stadiumCapacity: 68_740,
    matchesHosted: 6,
    timezone: 'America/Los_Angeles',
    utcOffset: -7,
    currency: 'USD',
    internetMbps: 360,
    costIndex: 4,
    baseNeighbourhoods: ['Capitol Hill', 'Ballard', 'Fremont'],
  },
  {
    slug: 'toronto',
    name: 'Toronto',
    country: 'CA',
    countryName: 'Canada',
    countryCode: 'CA',
    stadium: 'BMO Field',
    stadiumCapacity: 45_500,
    matchesHosted: 6,
    timezone: 'America/Toronto',
    utcOffset: -4,
    currency: 'CAD',
    internetMbps: 320,
    costIndex: 4,
    baseNeighbourhoods: ['Downtown', 'King West', 'The Annex'],
  },
  {
    slug: 'vancouver',
    name: 'Vancouver',
    country: 'CA',
    countryName: 'Canada',
    countryCode: 'CA',
    stadium: 'BC Place',
    stadiumCapacity: 54_500,
    matchesHosted: 7,
    timezone: 'America/Vancouver',
    utcOffset: -7,
    currency: 'CAD',
    internetMbps: 300,
    costIndex: 4,
    baseNeighbourhoods: ['Yaletown', 'Gastown', 'Kitsilano'],
  },
  {
    slug: 'guadalajara',
    name: 'Guadalajara',
    country: 'MX',
    countryName: 'Mexico',
    countryCode: 'MX',
    stadium: 'Estadio Akron',
    stadiumCapacity: 49_850,
    matchesHosted: 4,
    timezone: 'America/Mexico_City',
    utcOffset: -6,
    currency: 'MXN',
    internetMbps: 220,
    costIndex: 2,
    baseNeighbourhoods: ['Chapultepec', 'Providencia', 'Lafayette'],
  },
  {
    slug: 'mexico-city',
    name: 'Mexico City',
    country: 'MX',
    countryName: 'Mexico',
    countryCode: 'MX',
    stadium: 'Estadio Azteca',
    stadiumCapacity: 87_000,
    matchesHosted: 5,
    timezone: 'America/Mexico_City',
    utcOffset: -6,
    currency: 'MXN',
    internetMbps: 250,
    costIndex: 2,
    baseNeighbourhoods: ['Roma Norte', 'Condesa', 'Polanco'],
  },
  {
    slug: 'monterrey',
    name: 'Monterrey',
    country: 'MX',
    countryName: 'Mexico',
    countryCode: 'MX',
    stadium: 'Estadio BBVA',
    stadiumCapacity: 53_500,
    matchesHosted: 4,
    timezone: 'America/Monterrey',
    utcOffset: -6,
    currency: 'MXN',
    internetMbps: 220,
    costIndex: 2,
    baseNeighbourhoods: ['San Pedro Garza García', 'Centro', 'Valle Oriente'],
  },
];

export const WC2026_CITY_MAP: Record<string, WC2026City> = Object.fromEntries(
  WC2026_CITIES.map((c) => [c.slug, c]),
);
